name: Test Work Flow
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push

jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my first job! Greetings!"