name: Test Work Flow
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push

jobs:
  FirstJob:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my first job! Greetings!"
      - run: echo "Current branch - ${{ github.ref_name }}"
      - run: exit 1
  DependantJob:
    needs: FirstJob
    runs-on: ubuntu-latest
    steps:
      - run: echo Dependant job is here!
