name: Build Unity with Cake 🚀

on:
  push:
    branches: [master, dev]
  workflow_dispatch: 

jobs:
  run-tests:
    name: Run tests
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Unity EditMode tests
        run: >
          "C:/Program Files/Unity/Hub/Editor/6000.2.6f2/Editor/Unity.exe"
          -batchmode -quit
          -projectPath .
          -runTests
          -testPlatform EditMode
          -testResults TestResults/editmode.xml
          -logFile -
      - name: Run PlayMode tests
        run: >
          "C:/Program Files/Unity/Hub/Editor/6000.2.6f2/Editor/Unity.exe"
          -batchmode -quit
          -projectPath .
          -runTests
          -testPlatform PlayMode
          -testResults TestResults/playmode.xml
  build-android:
    needs: run-tests
    name: Build Android
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Cake
        uses: cake-build/cake-action@v3
        with:
          verbosity: Diagnostic
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: artifacts