name: Log Actor Data WorkFlow
run-name: Log Actor
on: push

env:
    ACTOR: ${{ github.actor }}
    ACTOR_ID: ${{ github.actor_id }}
    EVENT: ${{ github.event_name }}
    JOB: ${{ github.job }}
    TRIGGERING_ACTOR: ${{ github.triggering_actor }}

jobs:    
  LogCurrentActor: 
    runs-on: ubuntu-latest    
    steps:
      - &common_actor_log
        - run: echo "Current ACTOR - ACTOR" |
            echo "Current EVENT - EVENT"
            echo "Current JOB - JOB"
            echo "Current TRIGGERING_ACTOR - TRIGGERING_ACTOR"
  DetailedActorLog:
    runs-on: ubuntu-latest
    steps:
      - run: *common_actor_log # issue
      - run: |
          echo "Log current actor"
          echo "------------------"          
      - run: |
          echo "Actor: $ACTOR"
          echo "Actor's id $ACTOR_ID"